baseURL = "https://www.nashome.cn/"
# website language
languageCode = "zh"
# [en, zh, ...] determines which i18n file to use
defaultContentLanguage = "zh"
# website title
title = "Blog My Life"
# theme
theme = "LoveIt"
# whether to use git commit log to generate lastmod record
enableGitInfo = false
# whether to include chinese/japanese/korean
hasCJKLanguage = true
# default amount of posts in each pages
paginate = 12
# whether to use emoji code
enableEmoji = true
# whether to use robots.txt
enableRobotsTXT = true
# [UA-XXXXXXXX-X] google analytics code
googleAnalytics = "UA-105751499-1"
# copyright description used only for seo schema
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# date format
dateFormatToUse = "2006-01-02"
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # whether to use HTML tags directly in the document
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Author Info
[author]
  name = "ZhaoQiang"
  link = ""

# Sitemap Info
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
#[Permalinks]
#  posts = ":year/:month/:filename"

# Menu Info
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "post"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "categories"
    weight = 3

#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "about"
#    weight = 4

#  [[menu.main]]
#    identifier = "zh"
#    pre = '<i class="fas fa-language fa-fw"></i>'
#    name = ""
#    title = "简体中文"
#    url = "https://hugo-loveit-zh.netlify.com"
#    weight = 5

[params]
  # LoveIt theme version
  version = "0.1.X"
  # site description
  description = "A blog recording my life"
  # site keywords
  keywords = ["Dynamics AX", "Github" ,"Linux", "Synology","HUGO","Tutorial","Technology"]
  # site default theme ("light", "dark", "auto")
  defaultTheme = "auto"
  # public git repo url to link lastmod git commit only then enableGitInfo is true
  gitRepo = ""

  # Header info
  [params.header]
    # desktop header mode ("fixed", "normal", "auto")
    #desktopMode = "auto"
    # mobile header mode ("fixed", "normal", "auto")
    #mobileMode = "auto"

  # Footer Copyright Info
  [params.footer]
    # Site creation time
    since = 2016
    # ICP info only in China (HTML format is allowed)
    icp = '<a href="http://www.beian.miit.gov.cn">沪ICP备17033498号</a>'
    # license info (HTML format is allowed)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Home Page Info
  [params.home]
    # Home Page Profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      #avatarURL = "images/avatar.png"
      avatarURL = "https://nashome-image-bucket.oss-accelerate.aliyuncs.com/Images/avatar.png?x-oss-process=style/thumbnail"
      # subtitle shown in home page
      subtitle = "Welcome to my blog !"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
    # Home Page Posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social Info in home page
  [params.social]
    GitHub = "ZhaoqiangCn"
    #Linkedin = "xxxx"
    #Twitter = "xxxx"
    Instagram = "zq19890000"
    Email = "zq19890000@gmail.com"
    #Facebook = "xxxx"
    Telegram = "jaoqiang"
    # Medium = "xxxx"
    # Gitlab = "xxxx"
    # Youtubelegacy = "xxxx"
    # Youtubecustom = "xxxx"
     Youtubechannel = "UCb71N1EWfn12QGEfZ-5GIQA?view_as=subscriber"
    # Tumblr ="xxxx"
    # Quora = "xxxx"
    # Keybase = "xxxx"
    # Pinterest = "xxxx"
    # Reddit = "xxxx"
    # Codepen = "xxxx"
    # FreeCodeCamp = "xxxx"
    # Bitbucket = "xxxx"
    # Stackoverflow = "xxxx"
    # Weibo = "xxxx"
    # Odnoklassniki = "xxxx"
    # VK = "xxxx"
    # Flickr = "xxxx"
    # Xing = "xxxx"
    # Snapchat = "xxxx"
    # Soundcloud = "xxxx"
    # Spotify = "xxxx"
    # Bandcamp = "xxxx"
    # Paypal = "xxxx"
    # Fivehundredpx = "xxxx"
    # Mix = "xxxx"
    # Goodreads = "xxxx"
    # Lastfm = "xxxx"
    # Foursquare = "xxxx"
    # Hackernews = "xxxx"
    # Kickstarter = "xxxx"
    # Patreon = "xxxx"
    # Steam = "xxxx"
    # Twitch = "xxxx"
    # Strava = "xxxx"
    # Skype = "xxxx"
    # Whatsapp = "xxxx"
    # Zhihu = "xxxx"
    # Douban = "xxxx"
    # Angellist = "xxxx"
    # Slidershare = "xxxx"
    # Jsfiddle = "xxxx"
    # Deviantart = "xxxx"
    # Behance = "xxxx"
    # Dribble = "xxxx"
    # Wordpress = "xxxx"
    # Vine = "xxxx"
    # Googlescholar = "xxxx"
    # Researchgate = "xxxx"
    # Mastodon = "xxxx"
    # MastodonPrefix = "https://mastodon.technology/"
    # Thingiverse = "xxxx"
    # Devto = "xxxx"
    # Gitea = "xxxx"
    # XMPP = "xxxx"
    # Matrix = "xxxx"
     Bilibili = "474553042"

  # Page config
  [params.page]
    # whether to show social share links in post page
    socialShare = true
    # whether to show link to Raw Markdown content of the post
    linkToMarkdown = true

  # Social Share Links in post page
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    Linkedin = true
    Whatsapp = true
    Pinterest = true
    Tumblr = true
    HackerNews = true
    # Reddit = true
    # VK = true
    # Buffer = true
    # Xing = true
    # Line = true
    # Instapaper = true
    # Pocket = true
    # Digg = true
    # Stumbleupon = true
    # Flipboard = true
     Weibo = true
    # Renren = true
    # Myspace = true
    # Blogger = true
    # Baidu = true
    # Odnoklassniki = true
    # Evernote = true
    # Skype = true
    # Trello = true
    # Mix = true

  # mathematical formulas (KaTeX)
  [params.math]
    enable = true
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
    # KaTeX extension copy_tex
    copyTex = true
    # KaTeX extension mhchem
    mhchem = true

  # CSS and JS Files CDN
  [params.cdn]
    ## for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">' 
    jquery_js = '<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.slim.min.js"></script>'
    fontawesomeFreeCSS = '<link href="https://cdn.bootcss.com/font-awesome/5.11.2/css/all.min.css" rel="stylesheet">'                           # 例如 '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    animateCSS = '<link href="https://cdn.bootcss.com/animate.css/3.7.2/animate.css" rel="stylesheet">'
    gitalkCSS = '<link href="https://cdn.bootcss.com/gitalk/1.5.0/gitalk.min.css" rel="stylesheet">'
    gitalkJS = '<script src="https://cdn.bootcss.com/gitalk/1.5.0/gitalk.min.js"></script>'
    valineJS = ''
    lazysizesJS = '<script src="https://cdn.bootcss.com/lazysizes/5.1.2/lazysizes.min.js"></script>'
    smoothScrollJS = '<script src="https://cdn.bootcss.com/smooth-scroll/16.1.0/smooth-scroll.polyfills.min.js"></script>'
    sharerJS = ''
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    mermaidJS = ''
    echartsJS = ''
    echartsMacaronsJS = ''
    typeitJS = '<script src="https://cdn.bootcss.com/typeit/6.0.3/typeit.min.js"></script>'
    aplayerCSS = ''
    aplayerJS = ''
    metingJS = ''

  # site verification code for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # Publisher Info just for SEO
  [params.publisher]
    name = "ZhaoQiang"
    [params.publisher.logo]
      url = ""
      width = 127
      height = 40

  # Website Log Info just for SEO
  [params.logo]
    url = ""
    width = 127
    height = 40

  # Website Image Info just for SEO
  [params.image]
    url = ""
    width = 800
    height = 600

  # Comment Config
  [params.comment]
    enable = true

    # Valine Comment Config (https://github.com/xCss/Valine)
    [params.comment.valine]
      enable = true
      appId = 'Bu42IhLNJc94WvCDKSsRwTqa-gzGzoHsz'
      appKey = 'bKSP5XiBoIHs8PyXC4uhGhqQ'
      placeholder = '说点什么吧...'
      notify = false
      verify = false
      avatar = "mm"
      # meta= ""
      pageSize = 10
      visitor = true
      recordIP = true

# Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
